spring:
  application:
    name: oficina
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/oficina}
    username: ${DB_USERNAME:oficina}
    password: ${DB_PASSWORD:oficina}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
